Hrabal/TemPy

tempy/tempy.py, tests/test_DOMElement.py
Created  methods:
bfs = breadth-first search 
dfs = depth-first-search . With some options: 'reverse' to search from right to left and 'order' to set the type of traversing algorithm -> Preorder, Postorder or Inorder.
=> Implemented tree traversing api for DOM elements

tempy/elements.py, tests/test_css.py
I figured since there's not exactly anyone else jumping up to take the issue and I already have this ready to go I'll submit the PR. This should resolve issue #34.
=> Css.update

index.md
I fixed some grammar in index.md and made it read slightly more smoothly. I will try to look over the rest of the documentation and proofread it as well.
=> Proofread index.md in the documentation

CONTRIBUTING.md, README.md
Trying to do something useful while familiarizing myself with github. Your project looked interesting as I've programmed mostly in Python and I'm learning HTML.
=> Doc corrections

CONTRIBUTING.md, README.md
Made a few changes to README.md and Contributing.md.
=> documentation edits

examples/static/sw-people.json, examples/templates/hello_world.py, examples/templates/render_list.py, examples/templates/star_wars.py, examples/templates/static_files.py, examples/tempy_examples.py
Fixes issue: #49 
This fixes the issue with the import in the existing examples in the project. I've added a file for sw-people.json, which can be modified if desired.
Perhaps this way of importing is not the best, because the namespace will be polluted, but this is the way it works in the project. Maybe I would suggest this as a future improvement
=> Examples fix and addition

tempy/widgets.py, tests/test_widgets.py
i tackled the title issue first.
i added a set_title method to the widget.py/TempyPage
Will love to know if i am on the right track. Need your guidiance.
=> opinion: need your comment/guidiance on my fix

examples/templates/table_example.py, examples/tempy_examples.py, tempy/elements.py, tempy/tags.py, tempy/widgets.py, tests/test_widgets.py
Implements methods in issue: #41 
Adds example: #17
Methods mentioned in issue are added as well as an example for each method that is implemented.
=> TempyTable methods addition

tempy/exceptions.py, tempy/tags.py, tempy/tempy.py, tests/test_DOMElement.py
=> Find method (examples included)

README.md
- Changed heading format to add visual uniformity. 
- Added missing backslash.
See #16
=> style: formatting, missing backslash

index.md
Hi, I made some minor grammatical tweaks to index.md which I feel make it a little clearer to understand. Feel free to merge if it seems alright! Thanks.
=> Index.md altered

README.md
Fixed wording in certain areas, as well as made commenting consistent before conjunctions throughout the whole document.
=> Fixed wording in certian areas as well as made commemnting consistent

examples/templates/session_example/login_page.py, examples/templates/session_example/session_routes.py, examples/templates/session_example/user_page.py, examples/tempy_examples.py
I was playing around with this, and made a small example to test it out. I thought it was cute, and as per the https://github.com/Hrabal/TemPy/issues/17 issue, felt it could be a PR. 
Includes /user_login, /user_page and /user_logout pages. I also included an app secret to allow sessions and a `super_secret_token` for it to work. This is not how sessions or users would work in an actual project, but it does allow for demonstrating TemPy forms and links. 
user/pass is admin/admin, as in all good auth examples :)
=> A very basic user session example.

README.md
Hello, I am still learning git so I tried to fix some grammatical errors in the readme file although there were only a few of them.
=> I tried to fix some grammatical errors

README.md, examples/README.md, getting_started.md, index.md
As per request, I merged my working branch with gh-pages. I hope I did this properly. Editing some grammar, consistent terminology, and a bit of copy-editing.
=> Copy-editing documentation

make_an_app/base_files.md, make_an_app/database.md, make_an_app/index.md, make_an_app/models.md, make_an_app/tempy.md, make_an_app/tempy_2.md, make_an_app/tempy_3.md, make_an_app/tempy_4.md
I have made minor copy edits such as spelling and grammar edits to the documents in the "make_an_app" section.
=> Minor Copy Edits

README.md
Hacktober's one of the lowest hanging fruits. I didn't find any more grammar changes that are required. The   readME seems clean now.
=> Made grammar and spelling changes

README.md
* Corrected some spelling/grammar mistakes in README.md
=> Correct grammar/spelling in README.md

examples/README.md, examples/templates/bootstrap_example.py
Hi,
Added some links from the examples page.
Will add some more examples, especially around bootstrap
Thanks
=> Added links from the examples page

examples/templates/form_components.py, examples/templates/homepage.py, examples/tempy_examples.py
https://github.com/Hrabal/TemPy/issues/17
=> Added form example

examples/templates/bootstrap_example2.py
* Converted the tags into iterables so the redundant lines can be removed , for eg 
instead of 
we can group the comments out in a list and use Tempy to render them 
thus reducing the number of lines and giving user idea how to avoid redundancy and ease out coding with <b>TemPy</b>
=> Modified the code of Bootstrap eg2 to make it more pythonic 

README.md
Changed "his" to "its", as "container" is a gender-less noun. On line 232 and 233
=> very minor grammatical changes

examples/static/render_chart.js, examples/static/setup_chart.js, examples/templates/chartjs_example.py, examples/templates/homepage.py, examples/tempy_examples.py
I've added an example that uses chart JS. i also added the prepare_chart.js and render_chart.js scripts in the static folder.
=> example for chart js
